---
kind: pipeline
type: docker
name: package-iso

steps:
  - name: build
    image: storehouse/image-builder
    commands:
      - ant package

  - name: prepare-upload
    image: storehouse/image-builder
    commands:
      - mkdir -p upload/iso
      - cp build/preseed.iso upload/iso/debian-storehouse-$DRONE_BUILD_NUMBER.iso
      - cp build/preseed.iso upload/debian-storehouse-latest.iso
      - sha256sum upload/debian-storehouse-latest.iso > upload/debian-storehouse-latest.iso.sha256
      - sha256sum upload/iso/debian-storehouse-$DRONE_BUILD_NUMBER.iso > upload/iso/debian-storehouse-$DRONE_BUILD_NUMBER.iso.sha256
      
  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 10.10.0.26
      username: iso
      password:
        from_secret: ftp_password
      port: 22
      target: /srv/iso/debian-storehouse/
      source: upload
      strip_components: 1

